version: "3"

services:
  front_end:
    image: knoxie2/front_end_app_testing:latest
    ports:
      - 5007:5001
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.env == staging]

  orders_service_testing:
    image: knoxie2/orders_api_testing:latest
    ports:
      - 5008:5001
      - 5009:443
    environment:
      MongoDB__Host: orders_Db_testing
      ASPNETCORE_ENVIRONMENT: Staging
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.env == staging]

  products_service_testing:
    image: knoxie2/products_api_testing:latest
    ports:
      - 5010:5001
      - 5011:443
    environment:
      MongoDB__Host: products_Db_testing
      ASPNETCORE_ENVIRONMENT: Staging
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.env == staging]

  orders_Db_testing:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --port 27020
    volumes:
      - .orders_Db:/data/db
    ports:
      - 27020:27020
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.env == staging]

  products_Db_testing:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --port 27021
    volumes:
      - .products_Db:/data/db
    ports:
      - 27021:27021
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.env == staging]
