version: "3.4"
services:
  front_end:
    # build: ./FrontEnd
    image: knoxie2/front_end_app_testing:latest
    restart: always
    ports:
      - 5001:80
      - 5002:443
    depends_on:
      - orders_service_testing
      - products_service_testing

  orders_service_testing:
    #build: ./OrdersApi
    image: knoxie2/orders_api_testing:latest
    restart: always
    ports:
      - 5003:80
      - 5004:443
    environment:
      MongoDB__Host: orders_Db_testing
    depends_on:
      - orders_Db_testing

  products_service_testing:
    # build: ./ProductsApi
    image: knoxie2/products_api_testting:latest
    restart: always
    ports:
      - 5005:80
      - 5006:443
    environment:
      MongoDB__Host: products_Db_testing
    depends_on:
      - products_Db_testing

  orders_Db_testing:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - .orders_Db:/data/db
    ports:
      - 27017:27017

  products_Db_testing:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --port 27018
    volumes:
      - .products_Db:/data/db
    ports:
      - 27018:27018
